### ISSUE TITLE
The localization fails if the second half begins

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_navigation#125]
The localization fails if the second half begins because we are not in init at the beginning. So we arent initialized correctly.

I don't know a solution for this issue, since ready it also called after a goal where we are on the field.

**Comment by SammyRamone** [comment]
There should be a `firstHalf` boolean. How about checking if this one switched from true to false?

**Comment by Flova** [comment]
This doesn't seem to be the case.
