### ISSUE TITLE
ROS 2 bitbots_localization

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/bitbots_navigation#152]

**Comment by NFiedler** [comment]
This requires https://github.com/bit-bots/dynamic_stack_decider/issues/73.

**Comment by jaagut** [comment]
Let's move on!

**Comment by Flova** [comment]
Still waits for the DSD

**Comment by SammyRamone** [comment]
will be closed by https://github.com/bit-bots/bitbots_navigation/pull/161
