### ISSUE TITLE
pose_particles are initialized in the middle of the field if the robot falls after starting the game

### ISSUE THREAD

**Issue by hendrikbrandt** [bit-bots/bitbots_navigation#155]
## Expected behavior
pose_particles are initialized at the sides again as it is done at the start of a game

## Current behavior
After starting the game the pose_particles are initialized at the 2 sides of one half.
If the robot then falls down before an accurate position can be found, the particles will reinitialize in the middle of the field or in the middle of a half-field.

Before falling down
![Screenshot from 2021-12-02 15-35-13](https://user-images.githubusercontent.com/45638790/144445488-14ed845b-5e90-4a72-b452-ba02faa680de.png)

While falling down (pose_particles die / are removed)
![Screenshot from 2021-12-02 15-35-38](https://user-images.githubusercontent.com/45638790/144445561-39ef2338-f628-4906-94ff-5b9fc59a5f26.png)

After reinitializing localisation:
![Screenshot from 2021-12-02 15-35-57](https://user-images.githubusercontent.com/45638790/144445663-e30e2446-31ff-4499-b61b-661ff68d82e6.png)

The robot now thinks he is in the middle of the field even though the robot is actually on the left or right side.

## Possible Solution
Currently the pose_particles are initialized around the estimated position before falling with noise. 
Instead, it would be better if the pose_particles keep their position while the robot is falling and aren't updated/removed. 
Once the robot is standing again and the localisation continues, noise could then be added to the previous positions of particles.

**Comment by Flova** [comment]
The possible solution is right, except that we lost the orientation during the fall, so we need to reinit the filter, but I am wondering a bit, because we have the feature, that if the robot does not walk far (0.5m or something similar) after a given initialization the initialization is reapplied. We added this for exactly this reason during the WorldCup and it was also tested quite a bit. Maybe you could check the states of the localization dsd during the described scenario and report what's broken with the current mechanism.

**Comment by Flova** [comment]
https://github.com/bit-bots/bitbots_navigation/blob/master/bitbots_localization/src/bitbots_localization/localization_dsd/localization.dsd#L14

**Comment by Flova** [comment]
Relevant PR #134

**Comment by jaagut** [comment]
I am not quite sure, if we ever got into this state

https://github.com/bit-bots/bitbots_navigation/blob/ab31292ed6c0e809a971c776cf5bf78f879322ea/bitbots_localization/src/bitbots_localization/localization_dsd/localization.dsd#L14

**Comment by Flova** [comment]
I don't understand what you mean. Sry.

**Comment by Flova** [comment]
I think the message declaring the state fallen state might only be published on a state change, so it might be the case that you started the stack when the robot was already fallen, so it never got to the got up state as it was never fallen down in the frame of reference of the localization. But this contradicts with the observation of the localization being stoped during the fall.

**Comment by Flova** [comment]
Was the behavior reproducable?

**Comment by hendrikbrandt** [comment]
> Was the behavior reproducable?

yes, multiple times, although it isn't always 100% consistent and depends on the time between starting the rosbag and the localisation.

**Comment by Flova** [comment]
Hmm okay

**Comment by hendrikbrandt** [comment]
The localization dsd does enter the GettingUpState and then the WalkedSinceLastInit state. However, it declares that it has walked enough and therefore initializes the particles at the "robots position" depite it being wrong.

It seems like the localization either takes longer than just 0.5m of walking in order to converge, or the robot doesn't correctly calculate the walked distance

**Comment by Flova** [comment]
I also thought about that. Maybe the odom error leads to the assumption that the robot walked more than it did. You could add some prints to the decision and print the odom data used for this calculation.

**Comment by hendrikbrandt** [comment]
it turns out the dsd decides that the robot walked because self.blackboard.last_init_odom_transform is None. It seems like the dsd tries to set the initial odom position before the tf buffer is initialized/filled.

For testing purposes I added `rospy.sleep(1)` before the initial odom position is set and it fixed both the error and the unintended localisation behaviour

**Comment by Flova** [comment]
Ah okay. I think you can adapt the timeout at the point where this error is raised to fix this problem then. The localization should wait longer for the odom data in this case. Not sure if you need to do this in both the python and cpp part of the localization.

**Comment by hendrikbrandt** [comment]
I made a branch and pr so we can easier talk about the changes that need to be made
