### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by RoboCary-cpu** [bit-bots/bitbots_navigation#159]
I have learned a lot from your code. Thank you!
Can you kindly provide the methold for generating the map.png which can evaluate the importance of the particle.

**Comment by SammyRamone** [comment]
Happy to hear :slightly_smiling_face: 
We have a script to generate the map.png here 
https://github.com/bit-bots/humanoid_league_misc/blob/master/humanoid_league_map_generator/generate_maps.py

**Comment by Flova** [comment]
I am happy to hear that. 

Here is the script that generates the maps according to the robocup rules. It not only produces a map of e.g. the lines but it also precalculates a non linear distance map or gaussian (depending in the class) based on that information. 
https://github.com/bit-bots/humanoid_league_misc/blob/master/humanoid_league_map_generator/generate_maps.py

Feel free to ask if you have any further questions.

**Comment by Flova** [comment]
> Happy to hear 🙂 We have a script to generate the map.png here https://github.com/bit-bots/humanoid_league_misc/blob/master/humanoid_league_map_generator/generate_maps.py

Oh we simultaneously answered :D

**Comment by RoboCary-cpu** [comment]
> > Happy to hear slightly_smiling_face We have a script to generate the map.png here https://github.com/bit-bots/humanoid_league_misc/blob/master/humanoid_league_map_generator/generate_maps.py
> 
> Oh we simultaneously answered :D

Thank you for replying. I have another problem, have you takon the boundary and crossing into consideration so far, since the factor in the config is set to be zero?

**Comment by Flova** [comment]
We are currently only using the line point cloud. The other ones should work with some parameter tuning, but using only the lines worked so well, that we don't activated the other ones. We are using the line segmentation from our vision without further processing like hough lines or something similar. It is done by projecting the line pixels onto the field resulting in a point cloud of line points.
