### ISSUE TITLE
Reset localization when going to initial

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_navigation#181]
Referee simulation runs 120 real time seconds before "starting" the game.
During that time, the localization already begins to converge, but we can not yet move our head to collect more lines.

This could, depending on the start position, result in a wrong localization.
This also evades our localization pause at the game start where we stand still but look around.

**Comment by Flova** [comment]
As seen [here](https://github.com/bit-bots/bitbots_navigation/blob/210ba623cf16079b3e4d6a0f4edda972b1ec2a29/bitbots_localization_handler/bitbots_localization_handler/localization_dsd/localization.dsd#L24) the localization initializes during the transition to ready for exactly this reason. The localization runs before that, but we are not allowed to move and initialize it on the init to ready transition, so this doesn't matter imo. We could deactivate the localization in the beginning, but I don't see real benefits in that (other than the increased complexity). This is also the reason we stand and look around in the beginning, as we initialize the localization when we are able to look around and need to wait a few seconds for it to converge.
