### ISSUE TITLE
Localization dies when starting

### ISSUE THREAD

**Issue by val-ba** [bit-bots/bitbots_navigation#192]
There is no map frame and different nodes state that when doing a tf transform.
I started rl bitbots_bringup simulator_teamplayer.launch game_controller:=false and rr humanoid_league_game_controller sim_gamestate.py in webots.
When starting  rl bitbots_bringup simulator_teamplayer.launch game_controller:=false and localization:=false and rl bitbots_localization localization.launch, one can see that it will not start correctly.
I dont really know what causes this issue as I looked at the recent adjustments in the localization and it looks fine.
## Steps to Reproduce

1. rl bitbots_bringup simulator_teamplayer.launch game_controller:=false and localization:=false
2.  rl bitbots_localization localization.launch
3. watch the dsd in rqt e.g.
...

## Context (Environment)

- [ ] RViz
- [ ] Simulator
- [ ] Robot
- [ ] Local

**Comment by Flova** [comment]
Has this been resolved?

**Comment by val-ba** [comment]
> Has this been resolved?

It has been resolved by deleting and recloning the meta. So technically no, but I cannot reproduce it anymore

**Comment by Flova** [comment]
Okay

**Comment by Flova** [comment]
Weird
