### ISSUE TITLE
Check state distributions

### ISSUE THREAD

**Issue by MonsterUntermBett** [bit-bots/bitbots_navigation#21]
Check if all necessary kinds of state distributions are covered and delete unnecessary ones.
Check if values from config are used.
https://github.com/bit-bots/bitbots_navigation/blob/58c98855faf0d1bd8202b542a2ed11126519f237/bitbots_localization/src/StateDistribution.cpp#L7

**Comment by Flova** [comment]
@MonsterUntermBett what distributions are unnecessary in your opinion? The list seems quite complete?

**Comment by MonsterUntermBett** [comment]
don't know anymore.. I think it was more meant to be a reminder to check if they make sense for games..
