### ISSUE TITLE
check if moved particle is still on map

### ISSUE THREAD

**Issue by MonsterUntermBett** [bit-bots/bitbots_navigation#22]
after drift or diffuse particles can be outside the map/field. As this usually is not the case during a game, particle could be forced to stay on the map. 
Thrun, p. 116

**Comment by timonegk** [comment]
@hendrikbrandt is https://github.com/bit-bots/bitbots_navigation/tree/particle_outside_field finished and ready for a pull request?

**Comment by Flova** [comment]
@hendrikbrandt ping
