### ISSUE TITLE
include distance of measurement into rating

### ISSUE THREAD

**Issue by MonsterUntermBett** [bit-bots/bitbots_navigation#23]
often measurement that are further away on the robot, especially on its x-axis, are more unsure due to transformation, that closer ones. 
This could be included in to the probability calculation of the measurement.

**Comment by Flova** [comment]
Closing this as the the density is also lower at long distances, which has a naturally stabilizing effect.

**Comment by jaagut** [comment]
The density of what? I guess you don't mean the pose particles rather the projected line points?

**Comment by Flova** [comment]
Exactly. This feature would still be useful for goalposts etc. tho.
