### ISSUE TITLE
refactor localization.cpp

### ISSUE THREAD

**Issue by MonsterUntermBett** [bit-bots/bitbots_navigation#27]
- [x] get_motion: duration from config
- [x]  get_motion: use tools.cpp
- [x] delete publish pose 
- [x] publish_pose_with_cov: publish pose and map frame
- [x] improve publish_.._rating

**Comment by Flova** [comment]
The published pose with cov is currently the only way of determining the covariance isnt it?

**Comment by NFiedler** [comment]
Whats wrong with that?

**Comment by Flova** [comment]
>  delete publish pose

**Comment by JanGut** [comment]
@MonsterUntermBett 

> The published pose with cov is currently the only way of determining the covariance isnt it?

Then why did you suggest to delete the publishing?

**Comment by MonsterUntermBett** [comment]
> 
> 
> @MonsterUntermBett
> 
> > The published pose with cov is currently the only way of determining the covariance isnt it?
> 
> Then why did you suggest to delete the publishing?

The PoseWithCovariance was originally published by publish_pose_with_covariance. I just added publish_pose for my evaluation setup to publish my Evaluation message, which is not needed anymore.

**Comment by Flova** [comment]
But `publish_pose` is used to publish the transforms of the localization. I think we should rename `publish_pose` to `publish_tf` or something similar. Should the remaining evaluation message be completely deleted or moved to its own method? Have a look at our branch `refactor/misc_refactor` for our refactoring suggestions.

**Comment by MonsterUntermBett** [comment]
I think the Evaluation message can be deleted, because it is not really helpful for debugging.

**Comment by NFiedler** [comment]
While we don't need it for evaluation purposes anymore, we need it now to get a covariance matrix of the filtered position.

**Comment by MonsterUntermBett** [comment]
But isnt that included in the PoseWithCovariance message?

**Comment by NFiedler** [comment]
Okay, I thought we were talking about that one...
