### ISSUE TITLE
Localization: Clean up tf publisher

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_navigation#40]
The tf publisher should be cleaned up a bit. Therefore only the one ros conform localization map to odom tf should be published, while removing the mean, top5, top20, ... tfs.
Their capabilities could be added, by adding a (dynamic reconfigure) param, so the user can select if he wants to use the best `n` estimations.

**Comment by NFiedler** [comment]
I would suggest a ratio of the best particles to consider. This ratio should be configurable.
