### ISSUE TITLE
Make the noise in the drift function of the motion model configurable

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/bitbots_navigation#48]
## Is your feature request related to a problem? Please describe.

The current drift function of the motion model adds a noise to the measured drift. This noise should be configurable. 
## Describe the solution you'd like

The noise multiplied to the odometry signal in the motion model should be configurable by dyn reconf. . It is quite important to adapt this properly as it defines the measurement certainty of the odometry. For better usability, the (Gaussian I presume?) noise should be defined in a time delta of a whole second. Thus, it does not need to be changed with the rate of the filter. I think.

**Comment by Flova** [comment]
Closed in pull request #43.
