### ISSUE TITLE
Multiplication in observation model

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_navigation#58]
Evaluate usage of multiplication of measurements instead of addition in the observation model. As @MonsterUntermBett said this is the approach described in `Probabilistic robotics`, but I our case we see some problems with the impact of single false positives or the current handling of out of field particles.

This has to be evaluated and discussed in the future.

**Comment by Flova** [comment]
@MonsterUntermBett  I read some literature and came to the realization that a multiplication approach with values between 1 - 0 (as described in #20) makes sense if change the observation model quite a bit. This would result in a proper probabilistic approach.

First of all, a new distance function should be introduced that peaks with a gaussian like peak at the maximum and decays to the probability of a false positive/negative measurement as its global minimum. This prevents the distance function from nulling the whole observation in case of a false positive. Nevertheless, the probability of the whole observation gets pulled down in case of the false measurement.
This punishes false positives quite a bit, so false negatives need to be punished too. If we have look at laser scanners (which are referenced e.g. in `Probabilistic robotics`) they observe the whole measurement space every time. In our implementation, only the positive measured points in the observation space (our observation space is the projection of the image into the field space) influence our score. This is fatal because in the case of the multiplication more positive measurements are more likely to contain false positive and they are therefore heavily punished. We, therefore, need a constant observation space (the size number of pixels).
If a pixel is not classified as a line point the inverse (1 - x) of the distance function for the positive cases should be used and the negative measurements are also multiplied with the other measurements. This results in the whole observation space being processed.

This would result in a model that is punished if a line is measured at the wrong place and also if the line isn't measured at all. False positives/negatives are also punished, but the whole model should determine the probability of the observation and if we set the baseline of the distance functions higher, we are punishing the noise less but it gets also more likely to end up in exactly that state due to noise because the measurement itself has less impact.

Also if we say that the noise is approximately distributed equally across all measurements in a given time frame the ones with the better matching lines should have a better score over that time frame even with multiplication.

**Comment by MonsterUntermBett** [comment]
sounds good :)
