### ISSUE TITLE
Evaluate obstacle avoidance

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_navigation#78]
Currently, the obstacle inflation is disabled. Therefore, the robot's path around an obstacle is often too close to the obstacle. However, the inflation can not simply be increased because the ball is also published as an obstacle. Somehow, obstacles and balls should be treated differently by move_base.

**Comment by jaagut** [comment]
Is this now resolved with #105?

**Comment by Flova** [comment]
y
